#!/bin/bash
# @parseArger-begin
# @parseArger-help "Add a new email account to a molt" --option "help" --short-option "h"
# @parseArger-verbose --option "verbose" --level "0" --quiet-option "quiet"
_has_colors=0
if [ -t 1 ]; then
	ncolors=$(tput colors 2>/dev/null)
	if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
		_has_colors=1
	fi
fi
# @parseArger-declarations
# @parseArger pos name "Molt name to configure"
# @parseArger pos email "Email address to add"
# @parseArger opt password "Email password or app token" --short p --required
# @parseArger opt provider "Email provider preset" --short P --default-value "gmail" --one-of "gmail" --one-of "outlook" --one-of "custom"
# @parseArger opt smtp-host "SMTP server host" --short s
# @parseArger opt imap-host "IMAP server host" --short i
# @parseArger opt smtp-port "SMTP port" --default-value "587"
# @parseArger opt imap-port "IMAP port" --default-value "993"
# @parseArger opt from "From address (defaults to email)" --short f
# @parseArger flag default "Set as default account"
# @parseArger flag no-tls "Disable TLS"
# @parseArger flag no-starttls "Disable STARTTLS (for SMTP)"
# @parseArger-declarations-end

# @parseArger-utils
_helpHasBeenPrinted=1;
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
# @parseArger-utils-end

# @parseArger-parsing

__cli_arg_count=$#;

die()
{
	local _ret=1
    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
   	_ret="$2"
    fi
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	log "$1" -3 >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options=''
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# POSITIONALS ARGUMENTS
_positionals=();
_optional_positionals=();
_arg_name="";
_arg_email="";
# OPTIONALS ARGUMENTS
_arg_password=
_arg_provider="gmail"
_arg_smtp_host=
_arg_imap_host=
_arg_smtp_port="587"
_arg_imap_port="993"
_arg_from=
# FLAGS
_arg_default="off"
_arg_no_tls="off"
_arg_no_starttls="off"
# NESTED
_verbose_level="0";



print_help()
{
	_triggerSCHelp=1;

	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
		_helpHasBeenPrinted=0;
		echo -e "Add a new email account to a molt:"
	echo -e "	name: Molt name to configure"
	echo -e "	email: Email address to add"
	echo -e "	-p, --password <password>: Email password or app token [required]"
	echo -e "	-P, --provider <provider>: Email provider preset [one of 'gmail' 'outlook' 'custom'] [default: 'gmail']"
	echo -e "	-s, --smtp-host <host>: SMTP server host"
	echo -e "	-i, --imap-host <host>: IMAP server host"
	echo -e "	--smtp-port <port>: SMTP port [default: '587']"
	echo -e "	--imap-port <port>: IMAP port [default: '993']"
	echo -e "	-f, --from <address>: From address (defaults to email)"
	echo -e "	--default: Set as default account"
	echo -e "	--no-tls: Disable TLS"
	echo -e "	--no-starttls: Disable STARTTLS (for SMTP)"
	echo -e "Usage :
	$0 <name> <email> -p <password> [options]";
	fi

}

log() {
	local _arg_msg="${1}";
	local _arg_level="${2:-0}";
	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
		case "$_arg_level" in
			-3)
				_arg_COLOR="\033[0;31m";
				;;
			-2)
				_arg_COLOR="\033[0;33m";
				;;
			-1)
				_arg_COLOR="\033[1;33m";
				;;
			1)
				_arg_COLOR="\033[0;32m";
				;;
			2)
				_arg_COLOR="\033[1;36m";
				;;
			3)
				_arg_COLOR="\033[0;36m";
				;;
			*)
				_arg_COLOR="\033[0m";
				;;
		esac
		if [ "${_has_colors}" == "1" ]; then
			echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
		else
			echo "${_arg_msg}";
		fi
	fi
}

parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-p|--password)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_password="$2"
				shift
				;;
			--password=*)
				_arg_password="${_key##--password=}"
				;;
			-p*)
				_arg_password="${_key##-p}"
				;;
			
			-P|--provider)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_provider="$2"
				shift
				;;
			--provider=*)
				_arg_provider="${_key##--provider=}"
				;;
			-P*)
				_arg_provider="${_key##-P}"
				;;
			
			-s|--smtp-host)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_smtp_host="$2"
				shift
				;;
			--smtp-host=*)
				_arg_smtp_host="${_key##--smtp-host=}"
				;;
			-s*)
				_arg_smtp_host="${_key##-s}"
				;;
			
			-i|--imap-host)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_imap_host="$2"
				shift
				;;
			--imap-host=*)
				_arg_imap_host="${_key##--imap-host=}"
				;;
			-i*)
				_arg_imap_host="${_key##-i}"
				;;
			
			--smtp-port)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_smtp_port="$2"
				shift
				;;
			--smtp-port=*)
				_arg_smtp_port="${_key##--smtp-port=}"
				;;
			
			--imap-port)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_imap_port="$2"
				shift
				;;
			--imap-port=*)
				_arg_imap_port="${_key##--imap-port=}"
				;;
			
			-f|--from)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_from="$2"
				shift
				;;
			--from=*)
				_arg_from="${_key##--from=}"
				;;
			-f*)
				_arg_from="${_key##-f}"
				;;
			
			--default)
				_arg_default="on"
				;;
			--no-default)
				_arg_default="off"
				;;
			--tls)
				_arg_no_tls="off"
				;;
			--no-tls)
				_arg_no_tls="on"
				;;
			--starttls)
				_arg_no_starttls="off"
				;;
			--no-starttls)
				_arg_no_starttls="on"
				;;
			-h|--help)
				print_help;
				exit 0;
				;;
			-h*)
				print_help;
				exit 0;
				;;
			--verbose)
				if [ $# -lt 2 ];then
					_verbose_level="$((_verbose_level + 1))";
				else
					_verbose_level="$2";
					shift;
				fi
				;;
			--quiet)
				if [ $# -lt 2 ];then
					_verbose_level="$((_verbose_level - 1))";
				else
					_verbose_level="-$2";
					shift;
				fi
				;;
			
				*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="name email"
	if [ "${_positionals_count}" -gt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
	fi
	if [ "${_positionals_count}" -lt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}.
	${_positionals[*]}" 1;
	fi
}


assign_positional_args()
{
	local _positional_name _shift_for=$1;
	_positional_names="_arg_name _arg_email ";
	shift "$_shift_for"
	for _positional_name in ${_positional_names};do
		test $# -gt 0 || break;
		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
		local _match_var="_match${_positional_name}";
		local _regex="${!_match_var}";
		if [ -n "$_regex" ]; then
			[[ "${1}" =~ $_regex ]] || die "${_positional_name} does not match pattern: $_regex"
		fi
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
		shift;
	done
}

print_debug()
{
	print_help
	# shellcheck disable=SC2145
	echo "DEBUG: $0 $@";
	
	echo -e "\tname: ${_arg_name}";
	echo -e "\temail: ${_arg_email}";
	echo -e "\tpassword: ${_arg_password}";
	echo -e "\tprovider: ${_arg_provider}";
	echo -e "\tsmtp-host: ${_arg_smtp_host}";
	echo -e "\timap-host: ${_arg_imap_host}";
	echo -e "\tsmtp-port: ${_arg_smtp_port}";
	echo -e "\timap-port: ${_arg_imap_port}";
	echo -e "\tfrom: ${_arg_from}";
	echo -e "\tdefault: ${_arg_default}";
	echo -e "\tno-tls: ${_arg_no_tls}";
	echo -e "\tno-starttls: ${_arg_no_starttls}";

}


on_interrupt() {
	die Process aborted! 130;
}


parse_commandline "$@";
handle_passed_args_count;
assign_positional_args 1 "${_positionals[@]}";
trap on_interrupt INT;



# @parseArger-parsing-end
# print_debug "$@"
# @parseArger-end

# Main script logic

MOLT_NAME="$_arg_name"
EMAIL="$_arg_email"
PASSWORD="$_arg_password"
PROVIDER="$_arg_provider"

# Get project root
_PROJECT_ROOT="$(cd "$_SCRIPT_DIR/../../../.." && pwd)"
BASE_DIR="$_PROJECT_ROOT"
MOLT_HOME="$BASE_DIR/$MOLT_NAME"

# Validate molt exists
if [ ! -d "$MOLT_HOME" ]; then
	die "Molt '$MOLT_NAME' does not exist at $MOLT_HOME" 1
fi

# Check molt user exists
if ! id "$MOLT_NAME" &>/dev/null; then
	die "User '$MOLT_NAME' does not exist" 1
fi

# Generate account name from email
# mymail@gmail.com -> mymail__gmail
ACCOUNT_NAME=$(echo "$EMAIL" | sed 's/@/__/g' | sed 's/\./_/g')
log "Account name: $ACCOUNT_NAME" 2

# Set up provider defaults
if [ "$PROVIDER" = "gmail" ]; then
	SMTP_HOST="${_arg_smtp_host:-smtp.gmail.com}"
	IMAP_HOST="${_arg_imap_host:-imap.gmail.com}"
	SMTP_PORT="$_arg_smtp_port"
	IMAP_PORT="$_arg_imap_port"
elif [ "$PROVIDER" = "outlook" ]; then
	SMTP_HOST="${_arg_smtp_host:-smtp.office365.com}"
	IMAP_HOST="${_arg_imap_host:-outlook.office365.com}"
	SMTP_PORT="$_arg_smtp_port"
	IMAP_PORT="$_arg_imap_port"
else
	# Custom provider
	if [ -z "$_arg_smtp_host" ] || [ -z "$_arg_imap_host" ]; then
		die "Custom provider requires --smtp-host and --imap-host" 1
	fi
	SMTP_HOST="$_arg_smtp_host"
	IMAP_HOST="$_arg_imap_host"
	SMTP_PORT="$_arg_smtp_port"
	IMAP_PORT="$_arg_imap_port"
fi

FROM="${_arg_from:-$EMAIL}"

# TLS settings
if [ "$_arg_no_tls" = "on" ]; then
	TLS="off"
	SSL_TYPE="None"
else
	TLS="on"
	SSL_TYPE="IMAPS"
fi

if [ "$_arg_no_starttls" = "on" ]; then
	STARTTLS="off"
else
	STARTTLS="on"
fi

MSMTPRC="$MOLT_HOME/.msmtprc"
MBSYNCRC="$MOLT_HOME/.mbsyncrc"
MAILDIR_BASE="$MOLT_HOME/Maildir"

log "Configuring email for molt: $MOLT_NAME" 1
log "Email: $EMAIL" 2
log "Provider: $PROVIDER" 2
log "SMTP: $SMTP_HOST:$SMTP_PORT" 3
log "IMAP: $IMAP_HOST:$IMAP_PORT" 3

# Create Maildir structure for this account
ACCOUNT_MAILDIR="$MAILDIR_BASE/$ACCOUNT_NAME"
log "Creating Maildir: $ACCOUNT_MAILDIR" 2

sudo -u "$MOLT_NAME" mkdir -p "$ACCOUNT_MAILDIR"/{cur,new,tmp}
sudo -u "$MOLT_NAME" mkdir -p "$ACCOUNT_MAILDIR/Inbox"/{cur,new,tmp}

# Check if account already exists in msmtprc
if [ -f "$MSMTPRC" ] && grep -q "^account $ACCOUNT_NAME$" "$MSMTPRC"; then
	die "Account '$ACCOUNT_NAME' already exists in msmtp configuration" 1
fi

# Check if this will be the first account (to set as default)
FIRST_ACCOUNT="off"
if [ ! -f "$MSMTPRC" ] || ! grep -q "^account " "$MSMTPRC" 2>/dev/null; then
	FIRST_ACCOUNT="on"
fi

# Create or append to msmtprc
log "Configuring msmtp (SMTP)" 1

MSMTP_CONFIG="
# Account: $ACCOUNT_NAME ($EMAIL)
account $ACCOUNT_NAME
host $SMTP_HOST
port $SMTP_PORT
from $FROM
user $EMAIL
password $PASSWORD
tls $TLS
tls_starttls $STARTTLS
auth on
"

# Write msmtprc
if [ -f "$MSMTPRC" ]; then
	# Append to existing file
	# Remove default line if we're setting this as default
	if [ "$_arg_default" = "on" ] || [ "$FIRST_ACCOUNT" = "on" ]; then
		sudo -u "$MOLT_NAME" sed -i '/^default /d' "$MSMTPRC"
	fi
	echo "$MSMTP_CONFIG" | sudo -u "$MOLT_NAME" tee -a "$MSMTPRC" > /dev/null
else
	# Create new file
	echo "$MSMTP_CONFIG" | sudo -u "$MOLT_NAME" tee "$MSMTPRC" > /dev/null
fi

# Set default account if requested or if it's the first account
if [ "$_arg_default" = "on" ] || [ "$FIRST_ACCOUNT" = "on" ]; then
	echo "default $ACCOUNT_NAME" | sudo -u "$MOLT_NAME" tee -a "$MSMTPRC" > /dev/null
	log "Set as default account" 1
fi

# Set secure permissions on msmtprc
sudo chmod 600 "$MSMTPRC"
sudo chown "$MOLT_NAME:$MOLT_NAME" "$MSMTPRC"

# Create or append to mbsyncrc
log "Configuring mbsync (IMAP)" 1

MBSYNC_CONFIG="
# Account: $ACCOUNT_NAME ($EMAIL)
IMAPAccount $ACCOUNT_NAME
Host $IMAP_HOST
Port $IMAP_PORT
User $EMAIL
Pass $PASSWORD
SSLType $SSL_TYPE
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore $ACCOUNT_NAME-remote
Account $ACCOUNT_NAME

MaildirStore $ACCOUNT_NAME-local
Path $ACCOUNT_MAILDIR/
Inbox $ACCOUNT_MAILDIR/Inbox
Subfolders Verbatim

Channel $ACCOUNT_NAME
Master :$ACCOUNT_NAME-remote:
Slave :$ACCOUNT_NAME-local:
Create Both
Expunge Both
Patterns *
SyncState *
"

# Write mbsyncrc
if [ -f "$MBSYNCRC" ]; then
	echo "$MBSYNC_CONFIG" | sudo -u "$MOLT_NAME" tee -a "$MBSYNCRC" > /dev/null
else
	echo "$MBSYNC_CONFIG" | sudo -u "$MOLT_NAME" tee "$MBSYNCRC" > /dev/null
fi

# Set permissions on mbsyncrc
sudo chmod 600 "$MBSYNCRC"
sudo chown "$MOLT_NAME:$MOLT_NAME" "$MBSYNCRC"

# Set ownership of Maildir
sudo chown -R "$MOLT_NAME:$MOLT_NAME" "$MAILDIR_BASE"

log "" 0
log "Email account added successfully!" 1
log "Account: $ACCOUNT_NAME" 0
log "Email: $EMAIL" 0
log "" 0
log "Configuration files:" 2
log "  SMTP: $MSMTPRC" 0
log "  IMAP: $MBSYNCRC" 0
log "  Mail: $ACCOUNT_MAILDIR" 0
log "" 0
log "Configuring OpenClaw hooks and skill watcher..." 1

# Configure OpenClaw hooks for webhook (if not already configured)
OPENCLAW_CONFIG="$OPENCLAW_DIR/openclaw.json"
if [[ -f "$OPENCLAW_CONFIG" ]]; then
    # Check if hooks are enabled
    if ! jq -e '.hooks.enabled' "$OPENCLAW_CONFIG" &>/dev/null; then
        # Generate random token
        HOOK_TOKEN=$(openssl rand -hex 16)
        
        # Add hooks configuration
        jq --arg token "$HOOK_TOKEN" '.hooks = {"enabled": true, "token": $token, "path": "/hooks"}' "$OPENCLAW_CONFIG" > "${OPENCLAW_CONFIG}.tmp"
        mv "${OPENCLAW_CONFIG}.tmp" "$OPENCLAW_CONFIG"
        sudo chown "$MOLT_NAME:$MOLT_NAME" "$OPENCLAW_CONFIG"
        log "Added hooks configuration with auto-generated token" 2
    else
        log "Hooks already configured" 2
    fi
    
    # Check if skill watcher is enabled
    if ! jq -e '.skills.load.watch' "$OPENCLAW_CONFIG" &>/dev/null; then
        # Add skill watcher configuration
        jq '.skills.load.watch = true' "$OPENCLAW_CONFIG" > "${OPENCLAW_CONFIG}.tmp"
        mv "${OPENCLAW_CONFIG}.tmp" "$OPENCLAW_CONFIG"
        sudo chown "$MOLT_NAME:$MOLT_NAME" "$OPENCLAW_CONFIG"
        log "Enabled skill auto-reload (watch: true)" 2
    else
        log "Skill watcher already enabled" 2
    fi
else
    log "Warning: openclaw.json not found at $OPENCLAW_CONFIG" -1
fi

log "" 0
log "Setting up mail gatekeeper skill..." 1

# Create skill directory
SKILL_DIR="$MOLT_HOME/.openclaw/skills/mail-gatekeeper"
sudo -u "$MOLT_NAME" mkdir -p "$SKILL_DIR"

# Create skill from template if it doesn't exist
if [[ ! -f "$SKILL_DIR/SKILL.md" ]]; then
    # Copy and customize template
    TEMPLATE="$_PROJECT_ROOT/.docs/mail_skill_template.md"
    if [[ -f "$TEMPLATE" ]]; then
        # Replace placeholders
        ACCOUNTS_LIST=$(grep "^account " "$MSMTPRC" 2>/dev/null | awk '{print $2}' | grep -v "^default$" | tr '\n' ', ' | sed 's/, $//')
        sudo -u "$MOLT_NAME" sed \
            -e "s/{{MOLT_NAME}}/$MOLT_NAME/g" \
            -e "s|{{SKILL_PATH}}|$SKILL_DIR/SKILL.md|g" \
            -e "s/{{ACCOUNTS}}/${ACCOUNTS_LIST:-none}/g" \
            -e "s/{{RULES}}/Add your custom rules here./g" \
            "$TEMPLATE" > "$SKILL_DIR/SKILL.md"
        sudo chown "$MOLT_NAME:$MOLT_NAME" "$SKILL_DIR/SKILL.md"
        sudo chmod 644 "$SKILL_DIR/SKILL.md"
        log "Created skill: $SKILL_DIR/SKILL.md" 2
    fi
else
    log "Skill already exists at $SKILL_DIR/SKILL.md" 2
fi

log "" 0
log "Setting up automated mail checking..." 1

# Setup cron job (with staggered offset)
CRON_SETUP="$_SCRIPT_DIR/cron-setup"
if [[ -f "$CRON_SETUP" ]]; then
    sudo -u "$MOLT_NAME" bash "$CRON_SETUP" "$MOLT_NAME" --interval 30 2>&1 | while read -r line; do
        log "$line" 2
    done
else
    log "Warning: cron-setup script not found" -1
fi

log "" 0
log "✓ Email account setup complete!" 1
log "" 0
log "Next steps:" 1
log "  1. Edit rules: ./clmnt molt mail skill $MOLT_NAME" 0
log "  2. Test manually: sudo -u $MOLT_NAME $_SCRIPT_DIR/watch --verbose" 0
log "  3. Check status: ./clmnt molt mail cron-setup $MOLT_NAME --status" 0
log "" 0
log "Automated checking:" 1
log "  - Runs every 30 minutes as $MOLT_NAME user" 0
log "  - Only triggers AI when new mail arrives" 0
log "  - AI uses mail-gatekeeper skill to process emails" 0
log "  - Staggered schedule to prevent system spikes" 0
log "" 0
log "  Check emails manually: ./clmnt molt mail check $MOLT_NAME" 0
log "  Test SMTP: ./clmnt molt mail check $MOLT_NAME -t -r <recipient>" 0
