#!/bin/bash
# @parseArger-begin
# @parseArger-help "Execute a command as a molt user" --option "help" --short-option "h"
# @parseArger-verbose --option "verbose" --level "0" --quiet-option "quiet"
# @parseArger-leftovers leftovers
_has_colors=0
if [ -t 1 ]; then # Check if stdout is a terminal
	ncolors=$(tput colors 2>/dev/null)
	if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
		_has_colors=1
	fi
fi
# @parseArger-declarations
# @parseArger pos name "Molt name"
# @parseArger pos command "Command to execute"
# @parseArger opt base-dir "Base directory for molts" --short d --default-value "/home/didi/molts" --complete "directory"
# @parseArger flag verbose "Enable verbose output" --short v
# @parseArger-declarations-end

# @parseArger-utils
_helpHasBeenPrinted=1;
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
# @parseArger-utils-end

# @parseArger-parsing

__cli_arg_count=$#;

die()
{
	local _ret=1
    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
   	_ret="$2"
    fi
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	log "$1" -3 >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options=''
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# POSITIONALS ARGUMENTS
_positionals=();
_optional_positionals=();
_arg_name="";
_arg_command="";
# OPTIONALS ARGUMENTS
_arg_base_dir="/home/didi/molts"
# FLAGS
_arg_verbose="off"
# NESTED
# LEFTOVERS
_arg_leftovers=()
_verbose_level="0";



print_help()
{
	_triggerSCHelp=1;

	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
		_helpHasBeenPrinted=0;
		echo -e "Execute a command as a molt user:"
	echo -e "	name: Molt name"
	echo -e "	command: Command to execute"
	echo -e "	-d, --base-dir <base-dir>: Base directory for molts [default: ' /home/didi/molts ']"
	echo -e "	-v|--verbose|--no-verbose: Enable verbose output"
	echo -e "Usage :
	$0 <name> <command> [--base-dir <value>] [--[no-]verbose]";
	fi

}

log() {
	local _arg_msg="${1}";
	local _arg_level="${2:-0}";
	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
		case "$_arg_level" in
			-3)
				_arg_COLOR="\e[0;31m";
				;;
			-2)
				_arg_COLOR="\e[0;33m";
				;;
			-1)
				_arg_COLOR="\e[1;33m";
				;;
			1)
				_arg_COLOR="\e[0;32m";
				;;
			2)
				_arg_COLOR="\e[1;36m";
				;;
			3)
				_arg_COLOR="\e[0;36m";
				;;
			*)
				_arg_COLOR="\e[0m";
				;;
		esac
		if [ "${_has_colors}" == "1" ]; then
			echo -e "${_arg_COLOR}${_arg_msg}\e[0m";
		else
			echo "${_arg_msg}";
		fi
	fi
}

parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-d|--base-dir)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_base_dir="$2"
				shift
				;;
			--base-dir=*)
				_arg_base_dir="${1##--base-dir=}"
				;;
			-d*)
				_arg_base_dir="${1##-d}"
				;;
			
			-v|--verbose)
				_arg_verbose="on"
				;;
			--no-verbose)
				_arg_verbose="off"
				;;
			-h|--help)
				print_help;
				exit 0;
				;;
			-h*)
				print_help;
				exit 0;
				;;
			--verbose)
				if [ $# -lt 2 ];then
					_verbose_level="$((_verbose_level + 1))";
				else
					_verbose_level="$2";
					shift;
				fi
				;;
			--quiet)
				if [ $# -lt 2 ];then
					_verbose_level="$((_verbose_level - 1))";
				else
					_verbose_level="-$2";
					shift;
				fi
				;;
			
				*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="name command"
	if [ "${_positionals_count}" -lt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}.
	${_positionals[*]}" 1;
	fi
}


assign_positional_args()
{
	local _positional_name _shift_for=$1;
	_positional_names="_arg_name _arg_command ";
	_leftovers_count=$((${#_positionals[@]} - 2))
	for ((ii = 0; ii < _leftovers_count; ii++));do
		_positional_names="$_positional_names _arg_leftovers[$((ii + 0))]";
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names};do
		test $# -gt 0 || break;
		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
			local _match_var="_match${_positional_name}";
			local _regex="${!_match_var}";
			if [ -n "$_regex" ]; then
				[[ "${1}" =~ $_regex ]] || die "${_positional_name} does not match pattern: $_regex"
			fi
		fi
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
		shift;
	done
}

print_debug()
{
	print_help
	# shellcheck disable=SC2145
	echo "DEBUG: $0 $@";
	
	echo -e "	name: ${_arg_name}";
	echo -e "	command: ${_arg_command}";
	echo -e "	base-dir: ${_arg_base_dir}";
	echo -e "	verbose: ${_arg_verbose}";
	echo -e "	leftovers: ${_arg_leftovers[*]}";

}


on_interrupt() {
	die Process aborted! 130;
}


parse_commandline "$@";
handle_passed_args_count;
assign_positional_args 1 "${_positionals[@]}";
trap on_interrupt INT;




# @parseArger-parsing-end
# print_debug "$@"
# @parseArger-end

MOLT_NAME="$_arg_name"
BASE_DIR="$_arg_base_dir"
MOLT_HOME="$BASE_DIR/$MOLT_NAME"
COMMAND="$_arg_command"

# Check if molt exists
if [ ! -d "$MOLT_HOME" ]; then
  die "Molt '$MOLT_NAME' not found at $MOLT_HOME" 1
fi

# Check if user exists
if ! id "$MOLT_NAME" &>/dev/null; then
  die "User '$MOLT_NAME' does not exist" 1
fi

# Build full command with leftovers
FULL_COMMAND="$COMMAND"
if [ ${#_arg_leftovers[@]} -gt 0 ]; then
  FULL_COMMAND="$FULL_COMMAND ${_arg_leftovers[*]}"
fi

log "Executing as $MOLT_NAME: $FULL_COMMAND" 1

# Execute command as molt user
sudo -u "$MOLT_NAME" bash -c "cd '$MOLT_HOME' && $FULL_COMMAND"
